USE [master]
GO

/****** Object:  Database [IWMS]    Script Date: 11/9/2015 5:02:57 PM ******/
DROP DATABASE [IWMS]
GO

/****** Object:  Database [IWMS]    Script Date: 11/9/2015 5:02:57 PM ******/
CREATE DATABASE [IWMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IWMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\IWMS.mdf' , SIZE = 15360KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'IWMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\IWMS_log.ldf' , SIZE = 52416KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [IWMS] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IWMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IWMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IWMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IWMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IWMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IWMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [IWMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IWMS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [IWMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IWMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IWMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IWMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IWMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IWMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IWMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IWMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IWMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IWMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IWMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IWMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IWMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IWMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IWMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IWMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IWMS] SET RECOVERY FULL 
GO

ALTER DATABASE [IWMS] SET  MULTI_USER 
GO

ALTER DATABASE [IWMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IWMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IWMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IWMS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [IWMS] SET  READ_WRITE 
GO


